# Generated by Django 5.0.6 on 2025-10-07 20:02

import backend_app.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titre du document')),
                ('category', models.CharField(choices=[('contracts', 'Contrats de bail'), ('inventory', 'États des lieux'), ('receipts', 'Quittances'), ('insurance', 'Assurances')], max_length=50, verbose_name='Catégorie')),
                ('type', models.CharField(max_length=100, verbose_name='Type de document')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('content', models.TextField(blank=True, verbose_name='Contenu/Extrait')),
                ('file', models.FileField(upload_to=backend_app.models.document_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Fichier PDF')),
                ('size', models.CharField(blank=True, max_length=20, verbose_name='Taille du fichier')),
                ('pages', models.IntegerField(default=1, verbose_name='Nombre de pages')),
                ('tenant', models.CharField(max_length=255, verbose_name='Locataire')),
                ('property', models.CharField(max_length=255, verbose_name='Propriété')),
                ('status', models.CharField(choices=[('active', 'Actif'), ('completed', 'Terminé'), ('issued', 'Émis'), ('valid', 'Valide'), ('signed', 'Signé')], default='active', max_length=50, verbose_name='Statut')),
                ('date', models.DateField(verbose_name='Date du document')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'db_table': 'documents',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
