# Generated by Django 5.0.6 on 2025-10-08 18:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Propriete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('adresse', models.CharField(max_length=300, verbose_name='Adresse')),
                ('prix', models.DecimalField(decimal_places=2, help_text='Prix mensuel de location ou de vente', max_digits=12, verbose_name='Prix (FCFA)')),
                ('type_propriete', models.CharField(choices=[('Villa', 'Villa'), ('Studio', 'Studio'), ('Appartement', 'Appartement'), ('Duplex', 'Duplex'), ('Maison', 'Maison'), ('Bureau', 'Bureau'), ('Commerce', 'Commerce')], max_length=50, verbose_name='Type de propriété')),
                ('statut', models.CharField(choices=[('disponible', 'Disponible'), ('loué', 'Loué'), ('en_vente', 'En vente')], db_index=True, default='disponible', max_length=20, verbose_name='Statut')),
                ('locataire', models.CharField(blank=True, db_index=True, max_length=200, null=True, verbose_name='Locataire')),
                ('nombre_chambres', models.PositiveIntegerField(default=1, verbose_name='Nombre de chambres')),
                ('nombre_salles_bain', models.PositiveIntegerField(default=1, verbose_name='Nombre de salles de bain')),
                ('superficie', models.CharField(help_text='Ex: 120 m²', max_length=50, verbose_name='Superficie')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('image', models.CharField(default='🏠', max_length=10, verbose_name='Emoji/Icône')),
                ('date_ajout', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout")),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
            ],
            options={
                'verbose_name': 'Propriété',
                'verbose_name_plural': 'Propriétés',
                'db_table': 'proprietes',
                'ordering': ['-date_ajout'],
            },
        ),
        migrations.AlterField(
            model_name='document',
            name='category',
            field=models.CharField(choices=[('contracts', 'Contrats de bail'), ('inventory', 'États des lieux'), ('receipts', 'Quittances'), ('insurance', 'Assurances')], db_index=True, max_length=50, verbose_name='Catégorie'),
        ),
        migrations.AlterField(
            model_name='document',
            name='date',
            field=models.DateField(db_index=True, verbose_name='Date du document'),
        ),
        migrations.AlterField(
            model_name='document',
            name='pages',
            field=models.PositiveIntegerField(default=1, verbose_name='Nombre de pages'),
        ),
        migrations.AlterField(
            model_name='document',
            name='property',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Propriété'),
        ),
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('active', 'Actif'), ('completed', 'Terminé'), ('issued', 'Émis'), ('valid', 'Valide'), ('signed', 'Signé')], db_index=True, default='active', max_length=50, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='document',
            name='tenant',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Locataire'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['-date', '-created_at'], name='documents_date_2c9b45_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['category', 'status'], name='documents_categor_c827a1_idx'),
        ),
        migrations.AddField(
            model_name='propriete',
            name='proprietaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proprietes', to=settings.AUTH_USER_MODEL, verbose_name='Propriétaire'),
        ),
        migrations.AddIndex(
            model_name='propriete',
            index=models.Index(fields=['proprietaire', 'statut'], name='proprietes_proprie_a8fa74_idx'),
        ),
        migrations.AddIndex(
            model_name='propriete',
            index=models.Index(fields=['-date_ajout'], name='proprietes_date_aj_ed1173_idx'),
        ),
    ]
