# Generated by Django 5.2.7 on 2025-10-22 20:25

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('payment', 'Paiement'), ('maintenance', 'Maintenance'), ('contract', 'Contrat'), ('general', 'Général')], max_length=20, verbose_name='Type')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('message', models.TextField(verbose_name='Message')),
                ('is_read', models.BooleanField(default=False, verbose_name='Lu')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Nom complet')),
                ('phone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('id_number', models.CharField(max_length=50, verbose_name="Numéro d'identification")),
                ('lease_start_date', models.DateField(verbose_name='Date de début du bail')),
                ('lease_end_date', models.DateField(blank=True, null=True, verbose_name='Date de fin du bail')),
                ('monthly_rent', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Loyer mensuel')),
                ('security_deposit', models.CharField(max_length=50, verbose_name='Caution')),
                ('payment_method', models.CharField(choices=[('Mobile Money', 'Mobile Money'), ('Virement bancaire', 'Virement bancaire'), ('Espèces', 'Espèces'), ('Chèque', 'Chèque'), ('Orange Money', 'Orange Money'), ('MTN Money', 'MTN Money')], max_length=50, verbose_name='Méthode de paiement')),
                ('status', models.CharField(choices=[('À jour', 'À jour'), ('En retard', 'En retard'), ('active', 'Actif'), ('inactive', 'Inactif')], default='active', max_length=20, verbose_name='Statut')),
                ('signed_contract', models.FileField(blank=True, null=True, upload_to='tenants/contracts/', verbose_name='Contrat signé')),
                ('id_document', models.FileField(blank=True, null=True, upload_to='tenants/ids/', verbose_name="Document d'identité")),
                ('additional_notes', models.TextField(blank=True, verbose_name='Notes additionnelles')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('linked_property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenants', to='backend_app.property', verbose_name='Propriété liée')),
            ],
            options={
                'verbose_name': 'Locataire',
                'verbose_name_plural': 'Locataires',
                'db_table': 'tenants',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=50, verbose_name='Mois')),
                ('amount', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant')),
                ('payment_date', models.DateField(verbose_name='Date de paiement')),
                ('payment_method', models.CharField(choices=[('Orange Money', 'Orange Money'), ('MTN Money', 'MTN Money'), ('Mobile Money', 'Mobile Money'), ('Carte bancaire', 'Carte bancaire'), ('Virement bancaire', 'Virement bancaire'), ('Espèces', 'Espèces'), ('Chèque', 'Chèque')], max_length=50, verbose_name='Méthode de paiement')),
                ('status', models.CharField(choices=[('paid', 'Payé'), ('unpaid', 'Non payé'), ('À jour', 'À jour')], default='unpaid', max_length=20, verbose_name='Statut')),
                ('next_payment_date', models.DateField(blank=True, null=True, verbose_name='Date du prochain paiement')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('linked_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='backend_app.property', verbose_name='Propriété')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='backend_app.tenant', verbose_name='Locataire')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'db_table': 'payments',
                'ordering': ['-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(max_length=20, unique=True, verbose_name='ID de la demande')),
                ('request_type', models.CharField(choices=[('Plomberie', 'Plomberie'), ('Électricité', 'Électricité'), ('Climatisation', 'Climatisation'), ('Serrure', 'Serrure'), ('Peinture', 'Peinture'), ('Autre', 'Autre')], max_length=50, verbose_name='Type de problème')),
                ('location', models.CharField(choices=[('Cuisine', 'Cuisine'), ('Salle de bain', 'Salle de bain'), ('Chambre', 'Chambre'), ('Salon', 'Salon'), ('Balcon', 'Balcon'), ('Entrée', 'Entrée'), ('Autre', 'Autre')], max_length=50, verbose_name='Emplacement')),
                ('description', models.TextField(verbose_name='Description')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('in_progress', 'En cours'), ('resolved', 'Résolu'), ('rejected', 'Rejeté')], default='pending', max_length=20, verbose_name='Statut')),
                ('priority', models.CharField(choices=[('normal', 'Normal'), ('high', 'Élevé'), ('urgent', 'Urgent')], default='normal', max_length=20, verbose_name='Priorité')),
                ('provider', models.CharField(blank=True, max_length=200, null=True, verbose_name='Prestataire')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('linked_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_requests', to='backend_app.property', verbose_name='Propriété')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_requests', to='backend_app.tenant', verbose_name='Locataire')),
            ],
            options={
                'verbose_name': 'Demande de maintenance',
                'verbose_name_plural': 'Demandes de maintenance',
                'db_table': 'maintenance_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_type', models.CharField(choices=[('Location', 'Location'), ('Vente', 'Vente')], max_length=20, verbose_name='Type de contrat')),
                ('contract_purpose', models.CharField(max_length=200, verbose_name='Objet du contrat')),
                ('start_date', models.DateField(verbose_name='Date de début')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('amount', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant')),
                ('security_deposit', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Caution')),
                ('payment_method', models.CharField(max_length=50, verbose_name='Méthode de paiement')),
                ('payment_frequency', models.CharField(choices=[('Mensuel', 'Mensuel'), ('Trimestriel', 'Trimestriel'), ('Semestriel', 'Semestriel'), ('Annuel', 'Annuel')], max_length=20, verbose_name='Fréquence de paiement')),
                ('specific_rules', models.TextField(blank=True, verbose_name='Règles spécifiques')),
                ('insurance', models.TextField(blank=True, verbose_name='Assurance requise')),
                ('contract_pdf', models.FileField(blank=True, null=True, upload_to='contracts/', verbose_name='Contrat PDF')),
                ('additional_notes', models.TextField(blank=True, verbose_name='Notes additionnelles')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('linked_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='backend_app.property', verbose_name='Propriété')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='backend_app.tenant', verbose_name='Locataire')),
            ],
            options={
                'verbose_name': 'Contrat',
                'verbose_name_plural': 'Contrats',
                'db_table': 'contracts',
                'ordering': ['-created_at'],
            },
        ),
    ]
