# Generated by Django 5.2.7 on 2025-11-01 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0002_document_owner_property_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('proprietaire', 'Propriétaire'), ('locataire', 'Locataire'), ('admin', 'Administrateur Système')], default='locataire', max_length=20, verbose_name='Rôle'),
        ),
    ]
