# Generated by Django 5.2.7 on 2025-10-22 21:16

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0002_notification_tenant_payment_maintenancerequest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='currency',
            field=models.CharField(choices=[('FCFA', 'FCFA'), ('EUR', 'EUR'), ('USD', 'USD')], default='FCFA', max_length=10, verbose_name='Devise'),
        ),
        migrations.AddField(
            model_name='property',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='property',
            name='gps_lat',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Latitude GPS'),
        ),
        migrations.AddField(
            model_name='property',
            name='gps_lng',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Longitude GPS'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_balcony',
            field=models.BooleanField(default=False, verbose_name='Balcon disponible'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_garden',
            field=models.BooleanField(default=False, verbose_name='Jardin disponible'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_parking',
            field=models.BooleanField(default=False, verbose_name='Parking disponible'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_terrace',
            field=models.BooleanField(default=False, verbose_name='Terrasse disponible'),
        ),
        migrations.AddField(
            model_name='property',
            name='immediate_availability',
            field=models.BooleanField(default=True, verbose_name='Disponibilité immédiate'),
        ),
        migrations.AddField(
            model_name='property',
            name='lease_duration',
            field=models.CharField(blank=True, choices=[('6 mois', '6 mois'), ('12 mois', '12 mois'), ('24 mois', '24 mois'), ('Indéterminée', 'Indéterminée')], max_length=20, null=True, verbose_name='Durée du bail'),
        ),
        migrations.AddField(
            model_name='property',
            name='location',
            field=models.CharField(blank=True, max_length=200, verbose_name='Ville/Zone'),
        ),
        migrations.AddField(
            model_name='property',
            name='offer_type',
            field=models.CharField(choices=[('Location', 'Location'), ('Vente', 'Vente')], default='Location', max_length=20, verbose_name="Type d'offre"),
        ),
        migrations.AddField(
            model_name='property',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='properties', to=settings.AUTH_USER_MODEL, verbose_name='Propriétaire'),
        ),
        migrations.AlterField(
            model_name='property',
            name='prix',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Prix/Loyer mensuel'),
        ),
        migrations.AlterField(
            model_name='property',
            name='statut',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('occupé', 'Occupé'), ('loué', 'Loué'), ('en_vente', 'En vente'), ('vacant', 'Vacant')], default='disponible', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='property',
            name='type',
            field=models.CharField(choices=[('Appartement', 'Appartement'), ('Maison', 'Maison'), ('Villa', 'Villa'), ('Studio', 'Studio'), ('Terrain', 'Terrain'), ('Duplex', 'Duplex'), ('Penthouse', 'Penthouse'), ('Loft', 'Loft')], max_length=50, verbose_name='Type'),
        ),
    ]
