# Generated by Django 5.0.6 on 2025-10-08 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0002_propriete_alter_document_category_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='document',
            name='documents_date_2c9b45_idx',
        ),
        migrations.RemoveIndex(
            model_name='document',
            name='documents_categor_c827a1_idx',
        ),
        migrations.RemoveIndex(
            model_name='propriete',
            name='proprietes_proprie_a8fa74_idx',
        ),
        migrations.RemoveIndex(
            model_name='propriete',
            name='proprietes_date_aj_ed1173_idx',
        ),
        migrations.AlterField(
            model_name='document',
            name='category',
            field=models.CharField(choices=[('contracts', 'Contrats de bail'), ('inventory', 'États des lieux'), ('receipts', 'Quittances'), ('insurance', 'Assurances')], max_length=50, verbose_name='Catégorie'),
        ),
        migrations.AlterField(
            model_name='document',
            name='date',
            field=models.DateField(verbose_name='Date du document'),
        ),
        migrations.AlterField(
            model_name='document',
            name='pages',
            field=models.IntegerField(default=1, verbose_name='Nombre de pages'),
        ),
        migrations.AlterField(
            model_name='document',
            name='property',
            field=models.CharField(max_length=255, verbose_name='Propriété'),
        ),
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('active', 'Actif'), ('completed', 'Terminé'), ('issued', 'Émis'), ('valid', 'Valide'), ('signed', 'Signé')], default='active', max_length=50, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='document',
            name='tenant',
            field=models.CharField(max_length=255, verbose_name='Locataire'),
        ),
        migrations.AlterField(
            model_name='propriete',
            name='image',
            field=models.CharField(default='🏠', max_length=10, verbose_name='Icône'),
        ),
        migrations.AlterField(
            model_name='propriete',
            name='locataire',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Locataire'),
        ),
        migrations.AlterField(
            model_name='propriete',
            name='nombre_chambres',
            field=models.IntegerField(default=1, verbose_name='Nombre de chambres'),
        ),
        migrations.AlterField(
            model_name='propriete',
            name='nombre_salles_bain',
            field=models.IntegerField(default=1, verbose_name='Nombre de salles de bain'),
        ),
        migrations.AlterField(
            model_name='propriete',
            name='prix',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Prix mensuel'),
        ),
        migrations.AlterField(
            model_name='propriete',
            name='statut',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('loué', 'Loué'), ('en_vente', 'En vente')], default='disponible', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='propriete',
            name='superficie',
            field=models.CharField(max_length=50, verbose_name='Superficie'),
        ),
        migrations.AlterModelTable(
            name='propriete',
            table=None,
        ),
    ]
