# Generated by Django 5.2.7 on 2025-10-30 19:15

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0002_document_owner_property_currency_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_data', models.JSONField(default=dict, help_text='Données remplies par le locataire', verbose_name='Données du contrat')),
                ('tenant_signature', models.TextField(blank=True, null=True, verbose_name='Signature du locataire')),
                ('owner_signature', models.TextField(blank=True, null=True, verbose_name='Signature du propriétaire')),
                ('lease_start_date', models.DateField(verbose_name='Date de début du bail')),
                ('lease_end_date', models.DateField(blank=True, null=True, verbose_name='Date de fin du bail')),
                ('monthly_rent', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Loyer mensuel')),
                ('security_deposit', models.CharField(max_length=100, verbose_name='Caution')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('sent', 'Envoyé'), ('signed', 'Signé'), ('completed', 'Complété')], default='draft', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name="Date d'envoi")),
                ('signed_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de signature')),
                ('owner', models.ForeignKey(limit_choices_to={'role': 'proprietaire'}, on_delete=django.db.models.deletion.CASCADE, related_name='contract_templates', to=settings.AUTH_USER_MODEL, verbose_name='Propriétaire')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_templates', to='backend_app.property', verbose_name='Propriété')),
                ('tenant_user', models.ForeignKey(blank=True, limit_choices_to={'role': 'locataire'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_contracts', to=settings.AUTH_USER_MODEL, verbose_name='Locataire')),
            ],
            options={
                'verbose_name': 'Template de Contrat',
                'verbose_name_plural': 'Templates de Contrats',
                'db_table': 'contract_templates',
                'ordering': ['-created_at'],
            },
        ),
    ]
