# Generated by Django 5.2.7 on 2025-10-23 19:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0003_property_currency_property_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_date', models.DateTimeField(verbose_name='Date demandée')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Message optionnel')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('accepted', 'Acceptée'), ('rejected', 'Rejetée'), ('proposed', 'Nouvelle date proposée')], default='pending', max_length=20, verbose_name='Statut')),
                ('proposed_date', models.DateTimeField(blank=True, null=True, verbose_name='Date proposée')),
                ('owner_message', models.TextField(blank=True, null=True, verbose_name='Message du propriétaire')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit_requests', to='backend_app.property', verbose_name='Propriété')),
                ('tenant', models.ForeignKey(limit_choices_to={'role': 'locataire'}, on_delete=django.db.models.deletion.CASCADE, related_name='visit_requests', to=settings.AUTH_USER_MODEL, verbose_name='Locataire')),
            ],
            options={
                'verbose_name': 'Demande de visite',
                'verbose_name_plural': 'Demandes de visite',
                'db_table': 'visit_requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
