# Generated by Django 5.0.6 on 2025-10-08 19:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0003_remove_document_documents_date_2c9b45_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='propriete',
            name='locataire',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nom du locataire'),
        ),
        migrations.AddIndex(
            model_name='propriete',
            index=models.Index(fields=['proprietaire', 'statut'], name='backend_app_proprie_290131_idx'),
        ),
        migrations.AddIndex(
            model_name='propriete',
            index=models.Index(fields=['date_ajout'], name='backend_app_date_aj_451566_idx'),
        ),
    ]
