# Generated by Django 5.0.6 on 2025-10-08 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0004_alter_propriete_locataire_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Propriete',
        ),
    ]
