# Generated by Django 5.2.7 on 2025-10-24 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0004_visitrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitrequest',
            name='read_by_owner',
            field=models.BooleanField(default=False, verbose_name='Lu par le propriétaire'),
        ),
        migrations.AddField(
            model_name='visitrequest',
            name='read_by_tenant',
            field=models.BooleanField(default=False, verbose_name='Lu par le locataire'),
        ),
    ]
