# Generated by Django 5.2.7 on 2025-10-24 22:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0005_visitrequest_read_by_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='user',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'locataire'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenant_profile', to=settings.AUTH_USER_MODEL, verbose_name='Compte utilisateur'),
        ),
    ]
