# Generated by Django 5.2.7 on 2025-10-24 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0006_tenant_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='id_number',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name="Numéro d'identification"),
        ),
    ]
