# Generated by Django 5.2.7 on 2025-10-08 22:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0006_propriete_imagepropriete_documentpropriete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propriete',
            name='date_ajout',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date d'ajout"),
        ),
    ]
