# Generated by Django 5.2.7 on 2025-10-25 05:41

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0007_alter_tenant_id_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lease_start_date', models.DateField(verbose_name='Date de début du bail')),
                ('lease_end_date', models.DateField(blank=True, null=True, verbose_name='Date de fin du bail')),
                ('monthly_rent', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Loyer mensuel')),
                ('security_deposit', models.CharField(max_length=50, verbose_name='Caution')),
                ('payment_method', models.CharField(choices=[('Mobile Money', 'Mobile Money'), ('Virement bancaire', 'Virement bancaire'), ('Espèces', 'Espèces'), ('Chèque', 'Chèque'), ('Orange Money', 'Orange Money'), ('MTN Money', 'MTN Money')], max_length=50, verbose_name='Méthode de paiement')),
                ('status', models.CharField(choices=[('active', 'Actif'), ('terminated', 'Résilié'), ('expired', 'Expiré'), ('pending', 'En attente')], default='active', max_length=20, verbose_name='Statut')),
                ('signed_contract', models.FileField(blank=True, null=True, upload_to='locations/contracts/', verbose_name='Contrat signé')),
                ('additional_notes', models.TextField(blank=True, verbose_name='Notes additionnelles')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('terminated_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de résiliation')),
                ('owner', models.ForeignKey(limit_choices_to={'role': 'proprietaire'}, on_delete=django.db.models.deletion.CASCADE, related_name='owned_locations', to=settings.AUTH_USER_MODEL, verbose_name='Propriétaire')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='backend_app.property', verbose_name='Propriété')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='backend_app.tenant', verbose_name='Locataire')),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
                'db_table': 'locations',
                'ordering': ['-created_at'],
                'unique_together': {('tenant', 'property', 'status')},
            },
        ),
    ]
