# Generated by Django 5.2.7 on 2025-10-08 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0007_alter_propriete_date_ajout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagepropriete',
            name='propriete',
        ),
        migrations.DeleteModel(
            name='DocumentPropriete',
        ),
        migrations.DeleteModel(
            name='ImagePropriete',
        ),
        migrations.DeleteModel(
            name='Propriete',
        ),
    ]
