# Generated by Django 5.2.7 on 2025-10-11 13:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0008_remove_imagepropriete_propriete_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('adresse', models.CharField(max_length=300, verbose_name='Adresse')),
                ('prix', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Prix')),
                ('type', models.CharField(choices=[('Villa', 'Villa'), ('Studio', 'Studio'), ('Appartement', 'Appartement'), ('Duplex', 'Duplex')], max_length=50, verbose_name='Type')),
                ('statut', models.CharField(choices=[('disponible', 'Disponible'), ('loué', 'Loué'), ('en_vente', 'En vente')], default='disponible', max_length=20, verbose_name='Statut')),
                ('locataire', models.CharField(blank=True, max_length=200, null=True, verbose_name='Locataire')),
                ('chambres', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Chambres')),
                ('salles_de_bain', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Salles de bain')),
                ('superficie', models.CharField(max_length=50, verbose_name='Superficie')),
                ('date_ajout', models.DateField(auto_now_add=True, verbose_name="Date d'ajout")),
                ('image', models.FileField(blank=True, null=True, upload_to='properties/', verbose_name='Image/Vidéo')),
            ],
            options={
                'verbose_name': 'Propriété',
                'verbose_name_plural': 'Propriétés',
                'ordering': ['-date_ajout'],
            },
        ),
    ]
