# Generated by Django 5.2.7 on 2025-10-11 14:25

import backend_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0009_property'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='image',
            field=models.FileField(blank=True, max_length=200, null=True, upload_to=backend_app.models.property_image_path, verbose_name='Image/Vidéo'),
        ),
    ]
