# Generated by Django 5.2.7 on 2025-10-25 22:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0010_add_owner_to_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='owner',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'proprietaire'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL, verbose_name='Propriétaire'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='additional_notes',
            field=models.TextField(blank=True, verbose_name='Notes complémentaires'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='insurance',
            field=models.TextField(blank=True, verbose_name='Assurance'),
        ),
    ]
