# Generated by Django 5.2.7 on 2025-10-25 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0011_document_owner_alter_contract_additional_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('active', 'Actif'), ('terminated', 'Résilié'), ('expired', 'Expiré')], default='active', max_length=50, verbose_name='Statut'),
        ),
    ]
